---
<<<<<<< HEAD
version: "1.0"
=======
version: "3.3"
>>>>>>> dd614ab (updated config)
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - 13001:80
    environment:
    - TZ=America/New_York
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
  php:
    image: php:7-fpm
    container_name: php
    environment:
      - "TZ=America/New_York"
    volumes:
      - ./code:/code
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true